name: "build CI"
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install

      - name: Build Chrome
        run: yarn build:chrome

      - name: Build Firefox
        run: yarn build:firefox
