name: "build CI"
on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install

      - name: Build Chrome & Firefox
        run: yarn build:all

      - name: Upload extension zips
        uses: actions/upload-artifact@v4
        with:
          name: extension-zips
          path: dist/builds/*.zip
